# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxYOxMhkcmrBRXgTsTlnYcnC3ShwZN2X
"""

# Kerakli kutubxonalarni o'rnatish
!pip install scikit-learn

# Kutubxonalarni import qilish
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Iris ma'lumotlar to'plamini yuklash
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Ma'lumotlarni o'qitish va test to'plamlariga bo'lish
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model yaratish
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Bashorat qilish
y_pred = model.predict(X_test)

# Natijani baholash
print("Aniqlik:", accuracy_score(y_test, y_pred))