# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ef7tYSkUvPMkIjYTXQ_PDZvg7coXYKha
"""

# O'yin uchun zarur bo'lgan kutubxonalarni import qilamiz
import random
import time
from IPython.display import display, clear_output

# O'yin funksiyasini e'lon qilamiz
def click_game():
    print("Tugma bosish o'yiniga xush kelibsiz!")
    print("3 soniya ichida tumani tugmani bosish uchun tayyorlaning!")
    time.sleep(3)

    score = 0
    start_time = time.time()  # O'yin boshlanishi
    duration = 30  # O'yin davomiyligi (soniyalarda)

    while time.time() - start_time < duration:
        # Har bir bosish imkoniyatida tasodifiy joyni tanlaymiz
        print("Tugmani bosish uchun tayyor bo'ling...")
        time.sleep(random.uniform(1, 3))  # Tasodifiy kutish
        clear_output(wait=True)  # Oldingi natijalarni o'chirib tashlaymiz

        # Tugma bosish joyini ko'rsatamiz
        print("Bos! (Ctrl + C ni bosishni unutmang!)")
        score += 1  # Raqamni oshiramiz

    print(f"O'yin tugadi! Sizning ballingiz: {score}")

# O'yinni boshlaymiz
click_game()